[2023-02-23 16:46:47,876] {scheduler_job.py:182} INFO - Started process (PID=60) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:46:47,877] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:46:47,878] {logging_mixin.py:104} INFO - [2023-02-23 16:46:47,878] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:46:47,881] {logging_mixin.py:104} INFO - [2023-02-23 16:46:47,880] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:46:47,881] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:46:47,897] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2023-02-23 16:47:18,118] {scheduler_job.py:182} INFO - Started process (PID=112) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:47:18,118] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:47:18,119] {logging_mixin.py:104} INFO - [2023-02-23 16:47:18,119] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:47:18,121] {logging_mixin.py:104} INFO - [2023-02-23 16:47:18,120] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:47:18,121] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:47:18,134] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-23 16:47:48,742] {scheduler_job.py:182} INFO - Started process (PID=174) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:47:48,743] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:47:48,743] {logging_mixin.py:104} INFO - [2023-02-23 16:47:48,743] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:47:48,746] {logging_mixin.py:104} INFO - [2023-02-23 16:47:48,745] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:47:48,746] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:47:48,763] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2023-02-23 16:48:19,755] {scheduler_job.py:182} INFO - Started process (PID=226) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:48:19,756] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:48:19,756] {logging_mixin.py:104} INFO - [2023-02-23 16:48:19,756] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:48:19,758] {logging_mixin.py:104} INFO - [2023-02-23 16:48:19,758] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:48:19,759] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:48:19,773] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-23 16:48:50,540] {scheduler_job.py:182} INFO - Started process (PID=288) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:48:50,541] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:48:50,541] {logging_mixin.py:104} INFO - [2023-02-23 16:48:50,541] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:48:50,543] {logging_mixin.py:104} INFO - [2023-02-23 16:48:50,543] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:48:50,544] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:48:50,557] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-23 16:49:21,192] {scheduler_job.py:182} INFO - Started process (PID=340) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:49:21,193] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:49:21,194] {logging_mixin.py:104} INFO - [2023-02-23 16:49:21,194] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:49:21,196] {logging_mixin.py:104} INFO - [2023-02-23 16:49:21,195] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:49:21,196] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:49:21,210] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-23 16:49:52,009] {scheduler_job.py:182} INFO - Started process (PID=392) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:49:52,010] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:49:52,011] {logging_mixin.py:104} INFO - [2023-02-23 16:49:52,010] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:49:52,013] {logging_mixin.py:104} INFO - [2023-02-23 16:49:52,012] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:49:52,013] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:49:52,029] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-23 16:50:22,700] {scheduler_job.py:182} INFO - Started process (PID=454) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:50:22,701] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:50:22,701] {logging_mixin.py:104} INFO - [2023-02-23 16:50:22,701] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:50:22,703] {logging_mixin.py:104} INFO - [2023-02-23 16:50:22,703] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:50:22,704] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:50:22,774] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.076 seconds
[2023-02-23 16:50:53,597] {scheduler_job.py:182} INFO - Started process (PID=506) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:50:53,598] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:50:53,598] {logging_mixin.py:104} INFO - [2023-02-23 16:50:53,598] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:50:53,600] {logging_mixin.py:104} INFO - [2023-02-23 16:50:53,599] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:50:53,601] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:50:53,615] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-23 16:51:23,783] {scheduler_job.py:182} INFO - Started process (PID=567) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:51:23,784] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:51:23,785] {logging_mixin.py:104} INFO - [2023-02-23 16:51:23,785] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:51:23,787] {logging_mixin.py:104} INFO - [2023-02-23 16:51:23,787] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:51:23,788] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:51:23,803] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-23 16:51:54,487] {scheduler_job.py:182} INFO - Started process (PID=620) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:51:54,488] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:51:54,488] {logging_mixin.py:104} INFO - [2023-02-23 16:51:54,488] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:51:54,491] {logging_mixin.py:104} INFO - [2023-02-23 16:51:54,490] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:51:54,491] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:51:54,505] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-23 16:52:25,332] {scheduler_job.py:182} INFO - Started process (PID=682) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:52:25,333] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:52:25,333] {logging_mixin.py:104} INFO - [2023-02-23 16:52:25,333] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:52:25,335] {logging_mixin.py:104} INFO - [2023-02-23 16:52:25,335] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:52:25,335] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:52:25,349] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-23 16:52:55,950] {scheduler_job.py:182} INFO - Started process (PID=734) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:52:55,951] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:52:55,952] {logging_mixin.py:104} INFO - [2023-02-23 16:52:55,952] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:52:55,954] {logging_mixin.py:104} INFO - [2023-02-23 16:52:55,954] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:52:55,955] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:52:55,987] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.040 seconds
[2023-02-23 16:53:26,256] {scheduler_job.py:182} INFO - Started process (PID=787) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:53:26,257] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:53:26,258] {logging_mixin.py:104} INFO - [2023-02-23 16:53:26,257] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:53:26,260] {logging_mixin.py:104} INFO - [2023-02-23 16:53:26,259] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:53:26,260] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:53:26,273] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-23 16:53:57,187] {scheduler_job.py:182} INFO - Started process (PID=850) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:53:57,188] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:53:57,189] {logging_mixin.py:104} INFO - [2023-02-23 16:53:57,189] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:53:57,191] {logging_mixin.py:104} INFO - [2023-02-23 16:53:57,191] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:53:57,191] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:53:57,274] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.089 seconds
[2023-02-23 16:54:27,866] {scheduler_job.py:182} INFO - Started process (PID=902) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:54:27,866] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:54:27,867] {logging_mixin.py:104} INFO - [2023-02-23 16:54:27,867] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:54:27,869] {logging_mixin.py:104} INFO - [2023-02-23 16:54:27,868] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:54:27,869] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:54:27,883] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-23 16:54:58,651] {scheduler_job.py:182} INFO - Started process (PID=964) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:54:58,652] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:54:58,652] {logging_mixin.py:104} INFO - [2023-02-23 16:54:58,652] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:54:58,655] {logging_mixin.py:104} INFO - [2023-02-23 16:54:58,654] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:54:58,655] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:54:58,672] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.024 seconds
[2023-02-23 16:55:28,928] {scheduler_job.py:182} INFO - Started process (PID=1016) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:55:28,929] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:55:28,930] {logging_mixin.py:104} INFO - [2023-02-23 16:55:28,929] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:55:28,932] {logging_mixin.py:104} INFO - [2023-02-23 16:55:28,931] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:55:28,932] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:55:28,949] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2023-02-23 16:55:59,217] {scheduler_job.py:182} INFO - Started process (PID=1068) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:55:59,218] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:55:59,218] {logging_mixin.py:104} INFO - [2023-02-23 16:55:59,218] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:55:59,220] {logging_mixin.py:104} INFO - [2023-02-23 16:55:59,220] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:55:59,221] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:55:59,236] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-23 16:56:29,773] {scheduler_job.py:182} INFO - Started process (PID=1130) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:56:29,774] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:56:29,774] {logging_mixin.py:104} INFO - [2023-02-23 16:56:29,774] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:56:29,777] {logging_mixin.py:104} INFO - [2023-02-23 16:56:29,776] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:56:29,777] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:56:29,794] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.024 seconds
[2023-02-23 16:57:00,188] {scheduler_job.py:182} INFO - Started process (PID=1182) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:57:00,189] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:57:00,189] {logging_mixin.py:104} INFO - [2023-02-23 16:57:00,189] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:57:00,192] {logging_mixin.py:104} INFO - [2023-02-23 16:57:00,191] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:57:00,192] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:57:00,210] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.026 seconds
[2023-02-23 16:57:30,738] {scheduler_job.py:182} INFO - Started process (PID=1243) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:57:30,739] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:57:30,740] {logging_mixin.py:104} INFO - [2023-02-23 16:57:30,740] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:57:30,742] {logging_mixin.py:104} INFO - [2023-02-23 16:57:30,741] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:57:30,742] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:57:30,760] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.024 seconds
[2023-02-23 16:58:00,964] {scheduler_job.py:182} INFO - Started process (PID=1295) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:58:00,965] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:58:00,965] {logging_mixin.py:104} INFO - [2023-02-23 16:58:00,965] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:58:00,967] {logging_mixin.py:104} INFO - [2023-02-23 16:58:00,967] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:58:00,968] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:58:00,982] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-23 16:58:31,267] {scheduler_job.py:182} INFO - Started process (PID=1357) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:58:31,268] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:58:31,269] {logging_mixin.py:104} INFO - [2023-02-23 16:58:31,269] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:58:31,271] {logging_mixin.py:104} INFO - [2023-02-23 16:58:31,271] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:58:31,272] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:58:31,286] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-23 16:59:01,923] {scheduler_job.py:182} INFO - Started process (PID=1409) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:59:01,924] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:59:01,925] {logging_mixin.py:104} INFO - [2023-02-23 16:59:01,925] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:59:01,927] {logging_mixin.py:104} INFO - [2023-02-23 16:59:01,926] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:59:01,927] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:59:01,942] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-23 16:59:32,524] {scheduler_job.py:182} INFO - Started process (PID=1472) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:59:32,525] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 16:59:32,526] {logging_mixin.py:104} INFO - [2023-02-23 16:59:32,526] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:59:32,528] {logging_mixin.py:104} INFO - [2023-02-23 16:59:32,527] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 16:59:32,528] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 16:59:32,543] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-23 17:00:03,346] {scheduler_job.py:182} INFO - Started process (PID=1525) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:00:03,347] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:00:03,348] {logging_mixin.py:104} INFO - [2023-02-23 17:00:03,348] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:00:03,350] {logging_mixin.py:104} INFO - [2023-02-23 17:00:03,349] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:00:03,351] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:00:03,385] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.042 seconds
[2023-02-23 17:00:33,442] {scheduler_job.py:182} INFO - Started process (PID=1586) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:00:33,443] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:00:33,443] {logging_mixin.py:104} INFO - [2023-02-23 17:00:33,443] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:00:33,445] {logging_mixin.py:104} INFO - [2023-02-23 17:00:33,445] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:00:33,446] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:00:33,462] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-23 17:01:03,988] {scheduler_job.py:182} INFO - Started process (PID=1639) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:01:03,989] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:01:03,990] {logging_mixin.py:104} INFO - [2023-02-23 17:01:03,989] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:01:03,992] {logging_mixin.py:104} INFO - [2023-02-23 17:01:03,991] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:01:03,993] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:01:04,013] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.028 seconds
[2023-02-23 17:01:09,394] {scheduler_job.py:182} INFO - Started process (PID=1656) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:01:09,395] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:01:09,396] {logging_mixin.py:104} INFO - [2023-02-23 17:01:09,396] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:01:09,399] {logging_mixin.py:104} INFO - [2023-02-23 17:01:09,398] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:01:09,399] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:01:09,420] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.028 seconds
[2023-02-23 17:01:14,353] {scheduler_job.py:182} INFO - Started process (PID=1674) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:01:14,355] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:01:14,355] {logging_mixin.py:104} INFO - [2023-02-23 17:01:14,355] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:01:14,359] {logging_mixin.py:104} INFO - [2023-02-23 17:01:14,358] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:01:14,359] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:01:14,379] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.029 seconds
[2023-02-23 17:01:44,967] {scheduler_job.py:182} INFO - Started process (PID=1726) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:01:44,968] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:01:44,969] {logging_mixin.py:104} INFO - [2023-02-23 17:01:44,968] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:01:44,971] {logging_mixin.py:104} INFO - [2023-02-23 17:01:44,971] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:01:44,972] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:01:44,985] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-23 17:02:15,210] {scheduler_job.py:182} INFO - Started process (PID=1788) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:02:15,211] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:02:15,212] {logging_mixin.py:104} INFO - [2023-02-23 17:02:15,211] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:02:15,214] {logging_mixin.py:104} INFO - [2023-02-23 17:02:15,214] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:02:15,215] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:02:15,232] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.025 seconds
[2023-02-23 17:02:45,371] {scheduler_job.py:182} INFO - Started process (PID=1840) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:02:45,372] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:02:45,372] {logging_mixin.py:104} INFO - [2023-02-23 17:02:45,372] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:02:45,375] {logging_mixin.py:104} INFO - [2023-02-23 17:02:45,374] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:02:45,375] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:02:45,394] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.025 seconds
[2023-02-23 17:03:15,525] {scheduler_job.py:182} INFO - Started process (PID=1902) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:03:15,526] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:03:15,526] {logging_mixin.py:104} INFO - [2023-02-23 17:03:15,526] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:03:15,529] {logging_mixin.py:104} INFO - [2023-02-23 17:03:15,528] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:03:15,529] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:03:15,553] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.032 seconds
[2023-02-23 17:03:45,784] {scheduler_job.py:182} INFO - Started process (PID=1954) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:03:45,785] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:03:45,785] {logging_mixin.py:104} INFO - [2023-02-23 17:03:45,785] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:03:45,790] {logging_mixin.py:104} INFO - [2023-02-23 17:03:45,790] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:03:45,791] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:03:45,875] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.094 seconds
[2023-02-23 17:04:16,463] {scheduler_job.py:182} INFO - Started process (PID=2015) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:04:16,465] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:04:16,465] {logging_mixin.py:104} INFO - [2023-02-23 17:04:16,465] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:04:16,467] {logging_mixin.py:104} INFO - [2023-02-23 17:04:16,467] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:04:16,468] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:04:16,481] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-23 17:04:46,560] {scheduler_job.py:182} INFO - Started process (PID=2069) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:04:46,561] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:04:46,561] {logging_mixin.py:104} INFO - [2023-02-23 17:04:46,561] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:04:46,563] {logging_mixin.py:104} INFO - [2023-02-23 17:04:46,563] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:04:46,564] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:04:46,578] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-23 17:05:17,230] {scheduler_job.py:182} INFO - Started process (PID=2131) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:05:17,231] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:05:17,232] {logging_mixin.py:104} INFO - [2023-02-23 17:05:17,231] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:05:17,234] {logging_mixin.py:104} INFO - [2023-02-23 17:05:17,233] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:05:17,234] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:05:17,249] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-23 17:05:47,613] {scheduler_job.py:182} INFO - Started process (PID=2183) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:05:47,614] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:05:47,614] {logging_mixin.py:104} INFO - [2023-02-23 17:05:47,614] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:05:47,616] {logging_mixin.py:104} INFO - [2023-02-23 17:05:47,616] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:05:47,616] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:05:47,631] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-23 17:06:17,781] {scheduler_job.py:182} INFO - Started process (PID=2242) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:06:17,782] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:06:17,782] {logging_mixin.py:104} INFO - [2023-02-23 17:06:17,782] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:06:17,785] {logging_mixin.py:104} INFO - [2023-02-23 17:06:17,784] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:06:17,785] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:06:17,801] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2023-02-23 17:06:48,038] {scheduler_job.py:182} INFO - Started process (PID=2283) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:06:48,039] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:06:48,039] {logging_mixin.py:104} INFO - [2023-02-23 17:06:48,039] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:06:48,042] {logging_mixin.py:104} INFO - [2023-02-23 17:06:48,041] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:06:48,042] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:06:48,086] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.050 seconds
[2023-02-23 17:07:18,414] {scheduler_job.py:182} INFO - Started process (PID=2335) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:07:18,415] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:07:18,416] {logging_mixin.py:104} INFO - [2023-02-23 17:07:18,416] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:07:18,419] {logging_mixin.py:104} INFO - [2023-02-23 17:07:18,418] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:07:18,419] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:07:18,433] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-23 17:07:48,787] {scheduler_job.py:182} INFO - Started process (PID=2397) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:07:48,788] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:07:48,788] {logging_mixin.py:104} INFO - [2023-02-23 17:07:48,788] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:07:48,790] {logging_mixin.py:104} INFO - [2023-02-23 17:07:48,790] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:07:48,791] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:07:48,808] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.024 seconds
[2023-02-23 17:08:19,387] {scheduler_job.py:182} INFO - Started process (PID=2449) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:08:19,388] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:08:19,388] {logging_mixin.py:104} INFO - [2023-02-23 17:08:19,388] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:08:19,391] {logging_mixin.py:104} INFO - [2023-02-23 17:08:19,390] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:08:19,391] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:08:19,405] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-23 17:08:49,521] {scheduler_job.py:182} INFO - Started process (PID=2510) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:08:49,521] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:08:49,522] {logging_mixin.py:104} INFO - [2023-02-23 17:08:49,522] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:08:49,524] {logging_mixin.py:104} INFO - [2023-02-23 17:08:49,524] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:08:49,525] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:08:49,539] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-23 17:09:19,715] {scheduler_job.py:182} INFO - Started process (PID=2563) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:09:19,716] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:09:19,716] {logging_mixin.py:104} INFO - [2023-02-23 17:09:19,716] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:09:19,718] {logging_mixin.py:104} INFO - [2023-02-23 17:09:19,718] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:09:19,719] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:09:19,733] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-23 17:09:50,698] {scheduler_job.py:182} INFO - Started process (PID=2623) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:09:50,699] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:09:50,700] {logging_mixin.py:104} INFO - [2023-02-23 17:09:50,699] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:09:50,702] {logging_mixin.py:104} INFO - [2023-02-23 17:09:50,701] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:09:50,702] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:09:50,783] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.087 seconds
[2023-02-23 17:10:21,086] {scheduler_job.py:182} INFO - Started process (PID=2668) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:10:21,087] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:10:21,087] {logging_mixin.py:104} INFO - [2023-02-23 17:10:21,087] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:10:21,090] {logging_mixin.py:104} INFO - [2023-02-23 17:10:21,089] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:10:21,090] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:10:21,105] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-23 17:10:22,096] {scheduler_job.py:182} INFO - Started process (PID=2669) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:10:22,096] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:10:22,097] {logging_mixin.py:104} INFO - [2023-02-23 17:10:22,097] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:10:22,100] {logging_mixin.py:104} INFO - [2023-02-23 17:10:22,099] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:10:22,100] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:10:22,115] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-23 17:10:38,787] {scheduler_job.py:182} INFO - Started process (PID=2712) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:10:38,788] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:10:38,789] {logging_mixin.py:104} INFO - [2023-02-23 17:10:38,789] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:10:38,792] {logging_mixin.py:104} INFO - [2023-02-23 17:10:38,792] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:10:38,793] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:10:38,881] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.097 seconds
[2023-02-23 17:10:40,880] {scheduler_job.py:182} INFO - Started process (PID=2713) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:10:40,882] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 17:10:40,882] {logging_mixin.py:104} INFO - [2023-02-23 17:10:40,882] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:10:40,886] {logging_mixin.py:104} INFO - [2023-02-23 17:10:40,885] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 17:10:40,886] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 17:10:40,986] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.109 seconds
